### ISSUE TITLE
`talosctl dashboard` doesn't work when using Omni and node uuid/nodename as `-n`

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#491] opened 2024-07-25 22:27 UTC

**Comment by smira** [comment] 2024-07-26 12:06
I _think_ this got already fixed, at least I remember Utku doing a fix for this case.

**Comment by Unix4ever** [comment] 2024-07-26 16:49
I think this issue is different.
In talosctl you pass `-n talos-vpm-88g`, it gets resolved into `10.5.0.2` in Omni and works, then it returns back to talosctl with `Hostname=10.5.0.2` and it breaks the dashboard as it tries to find it by the name `talos-vpm-88g`.
I'm not sure if there's an easy way to fix it, but if we want to keep talosctl generic then we need to swap Hostname to `talos-vpm-88g` in the response.

**Comment by smira** [comment] 2024-07-26 16:54
I think that was exactly the fix, it tried to do one API call with each `node` and captures resolved address back from Talos API.

**Comment by utkuozdemir** [comment] 2024-07-31 14:09
I thought I fixed it that way, could it be a regression by the later changes on the name resolution code? In any case, I'll have a look.

**Comment by Unix4ever** [comment] 2024-08-01 12:03
I've checked that on the latest Talos, the problem seems to be there.

**Comment by utkuozdemir** [comment] 2024-08-02 14:51
This issue does not happen when talosctl and Talos versions are compatible.

However I indeed found an issue on the Monitor tab, which is now addressed by: https://github.com/siderolabs/talos/pull/9099

**Comment by utkuozdemir** [comment] 2024-08-07 14:38
I verified one more time, on my demo instance: the problem is not there on Talos `1.8.0-alpha.1`.
With the issue I fixed, dashboard is fully functional: https://github.com/siderolabs/talos/pull/9099

Hence, closing this.

**Closed by utkuozdemir** 2024-08-07 14:38 UTC
Labels: bug

**Comment by smira** [comment] 2024-08-07 14:39
> I verified one more time, on my demo instance: the problem is not there on Talos 1.8.0-alpha.1.

Is there any fix in 1.8 which didn't make its way into 1.7?

**Comment by utkuozdemir** [comment] 2024-08-07 14:42
> > I verified one more time, on my demo instance: the problem is not there on Talos 1.8.0-alpha.1.
> 
> Is there any fix in 1.8 which didn't make its way into 1.7?

There was an issue with the top section of the overview tab not loading on `1.7.4`, but I assumed it was caused by cli<>server incompatibility, but let me dig a bit further to find it out exactly.

**Comment by utkuozdemir** [comment] 2024-08-19 22:20
> > I verified one more time, on my demo instance: the problem is not there on Talos 1.8.0-alpha.1.
> 
> Is there any fix in 1.8 which didn't make its way into 1.7?

Just checked.

The newer talosctl version (`1.8.0-alpha...`) was not working properly with older Talos versions (`1.7.x`) due to some resource types not being available, which I addressed here: https://github.com/siderolabs/talos/pull/9202

But older CLI + newer Talos - no problem.

So I don't think we need a backport (though I didn't check talosctl 1.7 + talos 1.6 combination).
