### ISSUE TITLE
[bug] talosctl reboot doesn't work on omni nodes

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/omni#177] opened 2024-04-25 16:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Throws permission denied when issuing:

❯ talosctl -n talos-xxu-ebt reboot
◰ watching nodes: [talos-xxu-ebt]
    * talos-xxu-ebt: rpc error: code = PermissionDenied desc = not authorized

### Expected Behavior

`talosctl reboot` works to reboot the node in the same way that it does in the UI.

### Steps To Reproduce

Issue `talosctl reboot` against a worker node in an omni-based cluster.

**Comment by utkuozdemir** [comment] 2024-04-28 22:50
This is caused by the "action tracking" feature of `talosctl` that is enabled by default.

Action tracking feature shows the progress of the reboot. To be able to do that, it attempts to read the boot id before issuing the reboot GRPC call: https://github.com/siderolabs/talos/blob/main/cmd/talosctl/pkg/talos/action/tracker.go#L325-L341

We do not allow reading files even as admin in Omni.

Disabling action tracking by adding `--wait=false` to the command works as expected.

We can consider making the boot id readable (maybe expose it as a resource?) or using a fallback mechanism if we cannot read it.

**Comment by smira** [comment] 2024-04-29 10:22
We need two kinds of changes:

* `talosctl reboot` to fall back to "regular" mode if it gets permission denied
* figure out a way going forward (not sure what that would be?)

**Comment by utkuozdemir** [comment] 2024-04-29 15:23
Duplicate of https://github.com/siderolabs/talos/issues/7197

will track it on the issue above.

**Closed by utkuozdemir** 2024-04-29 15:23 UTC
Labels: bug

**Comment by ArcherSeven** [comment] 2024-04-30 16:36
@utkuozdemir how is this a duplicate of that card?  I am an admin, and have not attempted to use "--wait" in any form, and am hitting this issue.

**Comment by smira** [comment] 2024-04-30 16:38
@ArcherSeven `--wait=true` is the default, just use `--wait=false`.
